# Generated by Django 4.0.4 on 2022-05-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_note_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='camel_case_field',
            field=models.CharField(default='CamelCaseField', max_length=16),
        ),
    ]
