# Generated by Django 4.0.4 on 2022-06-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_note_camel_case_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='camel_case_field',
            field=models.CharField(default='From task with "*"', max_length=16),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Progress', 'Progress'), ('Done', 'Done'), ('Closed', 'Closed')], default='Active', max_length=16),
        ),
    ]
