# Generated by Django 4.0.4 on 2022-06-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_note_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
    ]
