# Generated by Django 4.0.4 on 2022-06-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_note_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='camel_case_field',
            field=models.CharField(default='From task with "*"', max_length=16, null=True),
        ),
    ]
