# Generated by Django 4.0.4 on 2022-06-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_note_camel_case_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created']},
        ),
    ]
