# Generated by Django 4.0.4 on 2022-06-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
