# Generated by Django 4.0.4 on 2022-06-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_note_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='project',
            new_name='project1',
        ),
    ]
