# Generated by Django 4.0.4 on 2022-06-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_rename_project_note_project1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='project1',
            new_name='project',
        ),
    ]
