# Generated by Django 4.0.4 on 2022-06-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_rename_project1_note_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='project',
        ),
    ]
